export const Typography = {
  family: {
    regular: 'Inter-Regular',
    medium: 'Inter-Medium',
    semiBold: 'Inter-SemiBold',
    bold: 'Inter-Bold',
  },
  displayLg: { fontSize: 32, lineHeight: 40, letterSpacing: -0.5 },
  displaySm: { fontSize: 28, lineHeight: 36, letterSpacing: -0.3 },
  h1: { fontSize: 24, lineHeight: 32, letterSpacing: -0.2 },
  h2: { fontSize: 20, lineHeight: 28, letterSpacing: -0.1 },
  h3: { fontSize: 18, lineHeight: 26, letterSpacing: 0 },
  h4: { fontSize: 16, lineHeight: 24, letterSpacing: 0 },
  bodyLg: { fontSize: 16, lineHeight: 24 },
  bodyMd: { fontSize: 14, lineHeight: 22 },
  bodySm: { fontSize: 13, lineHeight: 20 },
  labelLg: { fontSize: 14, lineHeight: 20, letterSpacing: 0.1 },
  labelMd: { fontSize: 12, lineHeight: 18, letterSpacing: 0.2 },
  labelSm: { fontSize: 11, lineHeight: 16, letterSpacing: 0.3 },
  caption: { fontSize: 12, lineHeight: 16, letterSpacing: 0.1 },
  captionSm: { fontSize: 11, lineHeight: 14 },
  mono: { fontSize: 13, lineHeight: 20, letterSpacing: 0 },
} as const;
