export const PERMISSIONS = {
  TASK_CREATE: 'task:create',
  TASK_READ_ALL: 'task:read:all',
  TASK_READ_OWN: 'task:read:own',
  TASK_UPDATE: 'task:update',
  TASK_UPDATE_STATUS: 'task:update:status',
  TASK_DELETE: 'task:delete',
  TASK_ASSIGN: 'task:assign',
  USER_READ: 'user:read',
  USER_CREATE: 'user:create',
  USER_UPDATE: 'user:update',
  USER_DEACTIVATE: 'user:deactivate',
  DEPT_MANAGE: 'dept:manage',
  REPORT_VIEW: 'report:view',
  REPORT_EXPORT: 'report:export',
  AUDIT_VIEW: 'audit:view',
  SYSTEM_CONFIG: 'system:config',
  FILE_UPLOAD: 'file:upload',
} as const;
